#!/bin/ksh

#=============================================================================
#
# 
#
# v1.0 - log any changes below here
#
#=============================================================================

# Preliminary check. We depend on variables being set by finish_master.sh.
# If we're not under its control, don't run or who knows what might happen.

[[ -z $IN_CONTROL ]] && \
{ print "This script should only be run by finish_master.sh"; exit 255; }

#-----------------------------------------------------------------------------
# VARIABLES

SCR_DESC="Increase randomness of TCP packet sequence numbering"
TCPFILE="${ROOT}/etc/default/inetinit"

#-----------------------------------------------------------------------------
# SCRIPT STARTS HERE

if [[ -f $TCPFILE ]]
then
	print -n "  upping randomness of TCP sequence numbering: "
	
	cp $TCPFILE "${TCPFILE}.tmp" && \
	sed -e '/^TCP_STRONG/s/1/2/' "${TCPFILE}.tmp" > $TCPFILE \
	&& print "ok" || print "failed"
	
	rm -f "${TCPFILE}.tmp"
else
	print "  ERROR: no inetinit file [ $TCPFILE ]"
	exit 1
fi

